#!/usr/bin/env bash
# Generate the Homebrew formula for a released version from its published
# checksums. Usage: scripts/make_formula.sh v0.8.0 > packaging/homebrew/rift.rb
set -euo pipefail

TAG="${1:?usage: make_formula.sh vX.Y.Z}"
VERSION="${TAG#v}"
BASE="https://github.com/exYze/rift/releases/download/${TAG}"

sums=$(curl -fsSL "${BASE}/checksums.txt")
sha() { echo "$sums" | awk -v f="$1" '$2 == f {print $1}'; }

for f in rift-aarch64-apple-darwin.tar.gz rift-x86_64-apple-darwin.tar.gz \
         rift-aarch64-unknown-linux-musl.tar.gz rift-x86_64-unknown-linux-musl.tar.gz; do
  [ -n "$(sha "$f")" ] || { echo "missing $f in checksums.txt" >&2; exit 1; }
done

cat <<EOF
# Generated by scripts/make_formula.sh ${TAG} — do not edit by hand.
class Rift < Formula
  desc "Fast terminal coding agent for local models — one binary, no runtimes"
  homepage "https://github.com/exYze/rift"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/rift-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha rift-aarch64-apple-darwin.tar.gz)"
    else
      url "${BASE}/rift-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha rift-x86_64-apple-darwin.tar.gz)"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE}/rift-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(sha rift-aarch64-unknown-linux-musl.tar.gz)"
    else
      url "${BASE}/rift-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha rift-x86_64-unknown-linux-musl.tar.gz)"
    end
  end

  def install
    bin.install "rift"
  end

  test do
    assert_match "rift #{version}", shell_output("#{bin}/rift --version")
  end
end
EOF
