#!/usr/bin/env bash
# Generate the winget manifest trio for a released version from its published
# checksums, ready for a PR to microsoft/winget-pkgs (or `wingetcreate submit`).
# Usage: scripts/make_winget.sh v1.9.0 [outdir]
#   outdir default: packaging/winget/<version>/
set -euo pipefail

TAG="${1:?usage: make_winget.sh vX.Y.Z [outdir]}"
VERSION="${TAG#v}"
BASE="https://github.com/exYze/rift/releases/download/${TAG}"
OUT="${2:-packaging/winget/${VERSION}}"

sums=$(curl -fsSL "${BASE}/checksums.txt")
SHA=$(echo "$sums" | awk '$2 == "rift-x86_64-pc-windows-msvc.zip" {print toupper($1)}')
[ -n "$SHA" ] || { echo "missing rift-x86_64-pc-windows-msvc.zip in checksums.txt" >&2; exit 1; }

mkdir -p "$OUT"

cat > "$OUT/exYze.rift.yaml" <<EOF
# Generated by scripts/make_winget.sh ${TAG} — do not edit by hand.
PackageIdentifier: exYze.rift
PackageVersion: ${VERSION}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$OUT/exYze.rift.installer.yaml" <<EOF
PackageIdentifier: exYze.rift
PackageVersion: ${VERSION}
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: rift.exe
    PortableCommandAlias: rift
Installers:
  - Architecture: x64
    InstallerUrl: ${BASE}/rift-x86_64-pc-windows-msvc.zip
    InstallerSha256: ${SHA}
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > "$OUT/exYze.rift.locale.en-US.yaml" <<EOF
PackageIdentifier: exYze.rift
PackageVersion: ${VERSION}
PackageLocale: en-US
Publisher: exYze
PublisherUrl: https://github.com/exYze
PackageName: rift
PackageUrl: https://github.com/exYze/rift
License: MIT
LicenseUrl: https://github.com/exYze/rift/blob/master/LICENSE
ShortDescription: Fast terminal coding agent for local models — one binary, no runtimes
Tags:
  - ai
  - agent
  - cli
  - coding
  - llm
  - ollama
  - tui
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

echo "wrote $OUT/{exYze.rift,exYze.rift.installer,exYze.rift.locale.en-US}.yaml" >&2
echo "submit: wingetcreate submit --token \$GITHUB_PAT $OUT  (or PR to microsoft/winget-pkgs)" >&2
