# Generated by scripts/make_formula.sh v0.8.1 — do not edit by hand.
class Rift < Formula
  desc "Fast terminal coding agent for local models — one binary, no runtimes"
  homepage "https://github.com/exYze/rift"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/exYze/rift/releases/download/v0.8.1/rift-aarch64-apple-darwin.tar.gz"
      sha256 "296505f593e22a103be959cc3a9ac93e4ebefdda444eeffa5b17030b2b438b5c"
    else
      url "https://github.com/exYze/rift/releases/download/v0.8.1/rift-x86_64-apple-darwin.tar.gz"
      sha256 "9188869c46f6dfee5b182084aaa3be75a1a9562d2dee8c92ee7de2d9377313ee"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/exYze/rift/releases/download/v0.8.1/rift-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e066fb54507c4ef8e0ed8cfbc50a9a7d65d11f66306ef784fc8c1cf1d6f01953"
    else
      url "https://github.com/exYze/rift/releases/download/v0.8.1/rift-x86_64-unknown-linux-musl.tar.gz"
      sha256 "dacee8e761a5895c82277daf5969fe6ea0896125062fe270558a2c9e1052c749"
    end
  end

  def install
    bin.install "rift"
  end

  test do
    assert_match "rift #{version}", shell_output("#{bin}/rift --version")
  end
end
