# Generated by scripts/make_formula.sh v0.8.0 — do not edit by hand.
class Rift < Formula
  desc "Fast terminal coding agent for local models — one binary, no runtimes"
  homepage "https://github.com/exYze/rift"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/exYze/rift/releases/download/v0.8.0/rift-aarch64-apple-darwin.tar.gz"
      sha256 "eea627eb99555683dc1c447d4a5d00358723fdcf991256ab29342449b26f9690"
    else
      url "https://github.com/exYze/rift/releases/download/v0.8.0/rift-x86_64-apple-darwin.tar.gz"
      sha256 "cace48e60442b26245796f4c5f71f3cab5f7d193ef1df1f55901f5a41d3fdf3f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/exYze/rift/releases/download/v0.8.0/rift-aarch64-unknown-linux-musl.tar.gz"
      sha256 "63e9832ed970c6e78760cfedbf9f02982fd1fd60a82a58864a4fa67f2c448532"
    else
      url "https://github.com/exYze/rift/releases/download/v0.8.0/rift-x86_64-unknown-linux-musl.tar.gz"
      sha256 "81ed9dfb4aee248fe0d3240644fcd152624603074ebadd72aa42f30a432cd1fc"
    end
  end

  def install
    bin.install "rift"
  end

  test do
    assert_match "rift #{version}", shell_output("#{bin}/rift --version")
  end
end
